sudo: required
env:
  - CC_TEST_REPORTER_ID=16d60a754f35d135681ebdc1e750743a3909ffac0f35f842f526ba2419cf0076
addons:
  chrome: stable
language: node_js
node_js:
  - "10.15.1"
notifications:
  slack:
    on_success: always
    rooms:
      - tensult:78YvxKn9R9EyXKMPWnKhQPVh#builds
cache:
  directories:
    - node_modules
services:
  - xvfb
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
script:
  - "npm run test:coverage"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
install:
  - "npm install"
